### ISSUE TITLE
Basic Setup - Protocol Error

### ISSUE THREAD

**Issue by gboxxx** [rn0x/HTMLSnapshot#1]
Followed Docker instructions and trying to do the Hello World example, but get the following error using cURL: 

```
[ERROR] 2024-12-29T03:35:15.310Z - Attempt 1 failed:
Error Details: {"stack":"Error: png screenshots do not support 'quality'.\n    at CdpPage.screenshot (file:///app/node_modules/puppeteer-core/lib/esm/puppeteer/api/Page.js:1014:31)\n    at async CdpPage.<anonymous> (file:///app/node_modules/puppeteer-core/lib/esm/puppeteer/util/decorators.js:164:24)\n    at async generateImageFromHtml (file:///app/index.mjs:191:32)\n    at async file:///app/index.mjs:85:28","message":"png screenshots do not support 'quality'."}
[INFO] 2024-12-29T03:35:15.440Z - Browser closed successfully.
[ERROR] 2024-12-29T03:35:17.444Z - Error generating image:
Error Details: {"stack":"Error: Protocol error: Connection closed. Most likely the page has been closed.\n    at assert (file:///app/node_modules/puppeteer-core/lib/esm/puppeteer/util/assert.js:15:15)\n    at CdpPage.close (file:///app/node_modules/puppeteer-core/lib/esm/puppeteer/cdp/Page.js:835:13)\n    at async generateImageFromHtml (file:///app/index.mjs:203:17)\n    at async file:///app/index.mjs:85:28","message":"Protocol error: Connection closed. Most likely the page has been closed."}
```
This happens well before my timeout setting of 30 sec. 

I've also tried messing with ENV: 

- development & production
- jpeg & png
- headless & not

When I visit the main url, I see: 
```
{"success":true,"message":"Welcome to the Image Generation API!","usage":{"endpoint":"/generate-image","method":"POST","description":"Generate an image from HTML template.","parameters":{"htmlTemplate":"HTML template as a string (required)","data":"An object containing dynamic data to replace in the template (optional)"},"exampleRequest":{"htmlTemplate":"<h1>{{title}}</h1>","data":{"title":"Hello World"}},"exampleResponse":{"success":true,"message":"Image generated successfully","image":"<base64-image>"}}}
```

Any advice? Been looking for a project like this for 2+ years so i'm stoked I came across your work!

**Comment by gboxxx** [comment]
Sorry, it appears my .ENV was not actually being registered for some reason. 

Thanks for the awesome work!
